In [1]:
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt

from pylab import rcParams
rcParams['figure.figsize'] = 10, 5
# import pandas_profiling

In [2]:
data = pd.read_csv('data/Cleaned_StateData_1.csv')
len(data), len(data.keys())

(2040, 532)

In [7]:
[key for key in data.keys() if 'Alcohol' in key]

['Alcoholic_Beverage_Tax', 'Alcoholic_Beverage_Lic']

In [17]:
data[data['State']=='WEST VIRGINIA'][['Year', 'Alcoholic_Beverage_Tax']]

      Year  Alcoholic_Beverage_Tax
48    2016                   17936
99    2015                   18159
150   2014                   17295
201   2013                   17690
252   2012                   17204
303   2011                   17524
354   2010                    8410
405   2009                    9479
456   2008                    9465
507   2007                    9012
558   2006                    9053
609   2005                    8646
660   2004                    8624
711   2003                    8652
762   2002                    8621
813   2001                    8197
864   2000                    8401
915   1999                    8080
966   1998                    8032
1017  1997                    7748
1068  1996                    7827
1119  1995                    7920
1170  1994                    7855
1221  1993                    7485
1272  1992                    8582
1323  1991                    8563
1374  1990                    8572
1425  1989                    8439
1476  1988                    8645
1527  1987                    7401
1578  1986                    7238
1629  1985                    6963
1680  1984                    6800
1731  1983                    6723
1782  1982                    6556
1833  1981                    5124
1884  1980                    5610
1935  1979                    6005
1986  1978                    5570
2037  1977                    5829